const EN_STRINGS={'1': 'ENGLISH · EVERY DAY', '2': 'A little vocabulary every day. Hear the word, see it in a sentence, and come back tomorrow for more.', '3': 'Your level', '4': 'Words per day', '5': '1 word', '6': '5 words', '7': '10 words', '8': 'View archive ↓', '9': 'Loading words…', '10': 'A LOOK AT TOMORROW', '11': 'Tomorrow', '12': 'YOUR REVIEW', '13': 'Learned words', '14': 'Save words here to revisit them whenever you like. They stay on this device.', '15': 'SINCE 25 SEPTEMBER 2026', '16': 'Archive', '17': 'Browse words from previous days. Change the level and daily word count above to explore different sets.', '18': 'Made by Scale Go · Free, no sign-up', '19': 'Back to Scale Go'};
const ES_STRINGS={'1': 'INGLÉS · CADA DÍA', '2': 'Un poco de vocabulario cada día. Escucha cómo se dice, mira un ejemplo y vuelve mañana a por más.', '3': 'Tu nivel', '4': 'Palabras al día', '5': '1 palabra', '6': '5 palabras', '7': '10 palabras', '8': 'Ver archivo ↓', '9': 'Cargando palabras…', '10': 'UN VISTAZO A MAÑANA', '11': 'Mañana', '12': 'TU REPASO', '13': 'Aprendidas', '14': 'Guárdalas aquí para volver a ellas cuando quieras. Se quedan en este dispositivo.', '15': 'DESDE EL 25 DE SEPTIEMBRE DE 2026', '16': 'Archivo', '17': 'Consulta las palabras de los días anteriores. Cambia el nivel y la cantidad arriba para ver el recorrido que prefieras.', '18': 'Hecho por Scale Go · Gratis y sin registro', '19': 'Volver a Scale Go'};
const enText={BACK:'← English',STREAK:'Streak',DAY:'day in a row',DAYS:'days in a row',STREAK_DEVICE:'Streak available on this device',LISTEN:'▶ Listen',PLAYING:'Playing…',AUDIO_ERROR:'Audio unavailable',EXAMPLE:'Example / Translation',LEARNED:'✓ Learned',MARK:'Mark as learned',TODAY:'Today',BEGINS:'The archive begins on 25 September 2026.',WORD:'word',WORDS:'words',NO_LEARNED:'No words marked as learned yet.',EMPTY_ARCHIVE:'Previous days will appear here from tomorrow.',FETCH_ERROR:'Could not load the words. Try reloading the page.'};
let uiLang=new URLSearchParams(location.search).get('lang')==='en'?'en':'es';
function setLanguage(lang){
  uiLang=lang;document.documentElement.lang=lang;
  document.querySelector('meta[name="description"]').content=lang==='en'?'Daily English vocabulary with real audio, examples and Spanish translations. Free, no sign-up.':'Una pequeña dosis diaria de inglés: palabras por nivel, pronunciación real y ejemplos con traducción. Gratis y sin registro.';
  document.querySelector('.back').textContent='← Scale Go';
  document.querySelector('.back').href='/';
  document.querySelector('.brand').href=lang==='en'?'/en/':'/';
  document.querySelector('footer a').href=lang==='en'?'/en/':'/';
  document.querySelectorAll('[data-i18n]').forEach(el=>{let key=el.dataset.i18n;el.textContent=(lang==='en'?EN_STRINGS:ES_STRINGS)[key]||el.textContent});
  document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===lang)));
  let url=new URL(location.href);if(lang==='en')url.searchParams.set('lang','en');else url.searchParams.delete('lang');history.replaceState(null,'',url);
  if(typeof render==='function'&&data)render();
}

const LEARNED_KEY='scalego-daily-learned',VISITS_KEY='scalego-daily-visits';
const START='2026-09-25',ZONE='Europe/Madrid';const level=document.getElementById('level'),count=document.getElementById('count'),cards=document.getElementById('cards'),days=document.getElementById('days');let data;
function madridDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function dayNumber(date){return Math.round((Date.parse(date+'T00:00:00Z')-Date.parse(START+'T00:00:00Z'))/86400000)}
function label(date){return new Intl.DateTimeFormat(uiLang==='en'?'en-GB':'es-ES',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'))}
function picks(date){const pool=data[level.value], n=Number(count.value), day=dayNumber(date);return Array.from({length:Math.min(n,pool.length)},(_,i)=>pool[((day*n+i)%pool.length+pool.length)%pool.length])}
function text(tag,value,cls){let el=document.createElement(tag);el.textContent=value;if(cls)el.className=cls;return el}
function learnedWords(){try{return JSON.parse(localStorage.getItem(LEARNED_KEY)||'[]')}catch{return []}}
function markButton(w){let b=text('button',learnedWords().includes(w.word)?(uiLang==='en'?enText.LEARNED:'✓ Aprendida'):(uiLang==='en'?enText.MARK:'Marcar como aprendida'),'learned-button');b.type='button';b.classList.toggle('active',learnedWords().includes(w.word));b.addEventListener('click',()=>{let old=learnedWords(),next=old.includes(w.word)?old.filter(x=>x!==w.word):[...old,w.word];localStorage.setItem(LEARNED_KEY,JSON.stringify(next));render()});return b}
function visit(date){try{let visits=JSON.parse(localStorage.getItem(VISITS_KEY)||'[]');if(!visits.includes(date)){visits.push(date);localStorage.setItem(VISITS_KEY,JSON.stringify(visits))}let set=new Set(visits),cursor=date,n=0;while(set.has(cursor)){n++;cursor=new Date(Date.parse(cursor+'T00:00:00Z')-86400000).toISOString().slice(0,10)}document.getElementById('streak').textContent=(uiLang==='en'?'↗ '+enText.STREAK+': ':'↗ Racha: ')+n+' '+(uiLang==='en'?(n===1?enText.DAY:enText.DAYS):(n===1?'día seguido':'días seguidos'))}catch{document.getElementById('streak').textContent=uiLang==='en'?enText.STREAK_DEVICE:'Racha disponible en este dispositivo'}}
function card(w,i){let article=text('article','', 'card'),head=text('div','', 'card-head'),left=text('div','');left.append(text('span',String(i+1).padStart(2,'0'),'number'),text('h2',w.word));if(w.ipa)left.append(text('div',w.ipa,'ipa'));let play=text('button',uiLang==='en'?enText.LISTEN:'▶ Escuchar','sound');play.type='button';play.setAttribute('aria-label',(uiLang==='en'?'Listen to the pronunciation of ':'Escuchar la pronunciación de ')+w.word);play.addEventListener('click',()=>{let audio=new Audio(w.audio);play.disabled=true;play.textContent=uiLang==='en'?enText.PLAYING:'Reproduciendo…';audio.onended=audio.onerror=()=>{play.disabled=false;play.textContent=uiLang==='en'?enText.LISTEN:'▶ Escuchar'};audio.play().catch(()=>{play.disabled=false;play.textContent=uiLang==='en'?enText.AUDIO_ERROR:'Audio no disponible'})});head.append(left,play);let ex=text('div','','example');ex.append(text('small',uiLang==='en'?enText.EXAMPLE:'Ejemplo / Example'),text('p',w.example),text('p',w.translation,'es'));article.append(head,text('div',w.meaning,'meaning'),text('p',uiLang==='en'?('In this example, “'+w.word+'” means “'+w.meaning+'” in Spanish.'):w.note,'note'),ex,markButton(w));return article}
function render(){if(!data)return;const now=madridDate();visit(now);document.getElementById('date').textContent=(uiLang==='en'?enText.TODAY:'Hoy')+' · '+label(now);cards.replaceChildren();days.replaceChildren();if(now<START){cards.textContent=uiLang==='en'?enText.BEGINS:'El archivo empieza el 25 de septiembre de 2026.';return}picks(now).forEach((w,i)=>cards.append(card(w,i)));let next=new Date(Date.parse(now+'T00:00:00Z')+86400000).toISOString().slice(0,10);document.getElementById('tomorrow-date').textContent=label(next);let preview=document.getElementById('preview');preview.replaceChildren();picks(next).forEach(w=>{let el=text('div','','preview-item');el.append(text('b',w.word),text('span',w.meaning));preview.append(el)});let learnedList=document.getElementById('learned-list');learnedList.replaceChildren();let all=Object.values(data).flat(),seen=new Set();for(let word of learnedWords()){let w=all.find(x=>x.word===word);if(w&&!seen.has(word)){learnedList.append(card(w,0));seen.add(word)}}if(!learnedList.children.length)learnedList.append(text('p',uiLang==='en'?enText.NO_LEARNED:'Aún no has marcado ninguna palabra.','empty')); for(let d=dayNumber(now)-1;d>=0;d--){let date=new Date(Date.parse(START+'T00:00:00Z')+d*86400000).toISOString().slice(0,10),details=text('details','','day'),summary=text('summary',''),list=text('ul','');summary.append(text('span',label(date)),text('span',count.value+' '+(uiLang==='en'?(count.value==='1'?enText.WORD:enText.WORDS):'palabras')+' · '+level.value));picks(date).forEach(w=>{let li=text('li',w.word+' · ');li.append(text('span',w.meaning));list.append(li)});details.append(summary,list);days.append(details)}if(!days.children.length)days.append(text('p',uiLang==='en'?enText.EMPTY_ARCHIVE:'El archivo se irá llenando a partir de mañana.','empty'))}
try{let saved=JSON.parse(localStorage.getItem('scalego-daily-word')||'{}');if(['A2','B1','B2'].includes(saved.level))level.value=saved.level;if([1,5,10].includes(saved.count))count.value=saved.count}catch{}for(let input of [level,count])input.addEventListener('change',()=>{localStorage.setItem('scalego-daily-word',JSON.stringify({level:level.value,count:Number(count.value)}));render()});fetch('words.json?v=20260926-bilingual',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Datos no disponibles');return r.json()}).then(json=>{data=json;render()}).catch(()=>{cards.textContent=uiLang==='en'?enText.FETCH_ERROR:'No se han podido cargar las palabras. Prueba a recargar la página.'});

for(const b of document.querySelectorAll("[data-lang]"))b.addEventListener("click",()=>setLanguage(b.dataset.lang));setLanguage(uiLang);
