
const LEARNED_KEY='scalego-daily-learned',VISITS_KEY='scalego-daily-visits';
const START='2026-09-25',ZONE='Europe/Madrid';const level=document.getElementById('level'),count=document.getElementById('count'),cards=document.getElementById('cards'),days=document.getElementById('days');let data;
function madridDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function dayNumber(date){return Math.round((Date.parse(date+'T00:00:00Z')-Date.parse(START+'T00:00:00Z'))/86400000)}
function label(date){return new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'))}
function picks(date){const pool=data[level.value], n=Number(count.value), day=dayNumber(date);return Array.from({length:Math.min(n,pool.length)},(_,i)=>pool[((day*n+i)%pool.length+pool.length)%pool.length])}
function text(tag,value,cls){let el=document.createElement(tag);el.textContent=value;if(cls)el.className=cls;return el}
function learnedWords(){try{return JSON.parse(localStorage.getItem(LEARNED_KEY)||'[]')}catch{return []}}
function markButton(w){let b=text('button',learnedWords().includes(w.word)?'✓ Aprendida':'Marcar como aprendida','learned-button');b.type='button';b.classList.toggle('active',learnedWords().includes(w.word));b.addEventListener('click',()=>{let old=learnedWords(),next=old.includes(w.word)?old.filter(x=>x!==w.word):[...old,w.word];localStorage.setItem(LEARNED_KEY,JSON.stringify(next));render()});return b}
function visit(date){try{let visits=JSON.parse(localStorage.getItem(VISITS_KEY)||'[]');if(!visits.includes(date)){visits.push(date);localStorage.setItem(VISITS_KEY,JSON.stringify(visits))}let set=new Set(visits),cursor=date,n=0;while(set.has(cursor)){n++;cursor=new Date(Date.parse(cursor+'T00:00:00Z')-86400000).toISOString().slice(0,10)}document.getElementById('streak').textContent='↗ Racha: '+n+' '+(n===1?'día seguido':'días seguidos')}catch{document.getElementById('streak').textContent='Racha disponible en este dispositivo'}}
function card(w,i){let article=text('article','', 'card'),head=text('div','', 'card-head'),left=text('div','');left.append(text('span',String(i+1).padStart(2,'0'),'number'),text('h2',w.word));if(w.ipa)left.append(text('div',w.ipa,'ipa'));let play=text('button','▶ Escuchar','sound');play.type='button';play.setAttribute('aria-label','Escuchar la pronunciación de '+w.word);play.addEventListener('click',()=>{let audio=new Audio(w.audio);play.disabled=true;play.textContent='Reproduciendo…';audio.onended=audio.onerror=()=>{play.disabled=false;play.textContent='▶ Escuchar'};audio.play().catch(()=>{play.disabled=false;play.textContent='Audio no disponible'})});head.append(left,play);let ex=text('div','','example');ex.append(text('small','Ejemplo / Example'),text('p',w.example),text('p',w.translation,'es'));article.append(head,text('div',w.meaning,'meaning'),text('p',w.note,'note'),ex,markButton(w));return article}
function render(){if(!data)return;const now=madridDate();visit(now);document.getElementById('date').textContent='Hoy · '+label(now);cards.replaceChildren();days.replaceChildren();if(now<START){cards.textContent='El archivo empieza el 25 de septiembre de 2026.';return}picks(now).forEach((w,i)=>cards.append(card(w,i)));let next=new Date(Date.parse(now+'T00:00:00Z')+86400000).toISOString().slice(0,10);document.getElementById('tomorrow-date').textContent=label(next);let preview=document.getElementById('preview');preview.replaceChildren();picks(next).forEach(w=>{let el=text('div','','preview-item');el.append(text('b',w.word),text('span',w.meaning));preview.append(el)});let learnedList=document.getElementById('learned-list');learnedList.replaceChildren();let all=Object.values(data).flat(),seen=new Set();for(let word of learnedWords()){let w=all.find(x=>x.word===word);if(w&&!seen.has(word)){learnedList.append(card(w,0));seen.add(word)}}if(!learnedList.children.length)learnedList.append(text('p','Aún no has marcado ninguna palabra.','empty')); for(let d=dayNumber(now)-1;d>=0;d--){let date=new Date(Date.parse(START+'T00:00:00Z')+d*86400000).toISOString().slice(0,10),details=text('details','','day'),summary=text('summary',''),list=text('ul','');summary.append(text('span',label(date)),text('span',count.value+' palabras · '+level.value));picks(date).forEach(w=>{let li=text('li',w.word+' · ');li.append(text('span',w.meaning));list.append(li)});details.append(summary,list);days.append(details)}if(!days.children.length)days.append(text('p','El archivo se irá llenando a partir de mañana.','empty'))}
try{let saved=JSON.parse(localStorage.getItem('scalego-daily-word')||'{}');if(['A2','B1','B2'].includes(saved.level))level.value=saved.level;if([1,5,10].includes(saved.count))count.value=saved.count}catch{}for(let input of [level,count])input.addEventListener('change',()=>{localStorage.setItem('scalego-daily-word',JSON.stringify({level:level.value,count:Number(count.value)}));render()});fetch('words.json').then(r=>{if(!r.ok)throw Error('Datos no disponibles');return r.json()}).then(json=>{data=json;render()}).catch(()=>{cards.textContent='No se han podido cargar las palabras. Prueba a recargar la página.'});
