'use strict';
const $=id=>document.getElementById(id),DAY=86400000,KEY='scalego:vocab:v1';
let units={},level='C1',queue=[],index=0,qIndex=0,score=0,voice=null;
const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today=()=>localDate(new Date());
const read=()=>{try{let d=JSON.parse(localStorage.getItem(KEY)||'{}');return d&&typeof d==='object'?d:{}}catch{return {}}};
const write=data=>{try{localStorage.setItem(KEY,JSON.stringify(data))}catch{}};
const show=id=>$(id).classList.remove('hidden'),hide=id=>$(id).classList.add('hidden');
const cardKey=c=>level+':'+c.id;
function dueCards(){const data=read();return units[level].cards.filter(c=>data[cardKey(c)]?.due && data[cardKey(c)].due<=today())}
function overview(){const u=units[level],due=dueCards().length;$('unitTag').textContent='UNIDAD 01 · '+level;$('unitTitle').textContent=u.topic;$('levelStatus').textContent=`${level} · ${u.topic}`;$('reviewStatus').textContent=due?`${due} palabra${due===1?'':'s'} pendiente${due===1?'':'s'} hoy. Empezarás por ellas.`:'No tienes repasos pendientes hoy. Puedes practicar toda la unidad.';document.querySelectorAll('.level').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.level===level)));show('unitIntro');['cardPanel','quizPanel','resultPanel'].forEach(hide)}
function chooseLevel(v){level=v;overview()}
function save(c,known){const data=read(),id=cardKey(c),old=data[id]||{step:0};let step=known?Math.min((Number.isInteger(old.step)?old.step:0)+1,4):0;const days=[1,3,7,14,30];const when=new Date();when.setDate(when.getDate()+days[step]);data[id]={step,due:localDate(when)};write(data)}
function start(cards){queue=[...cards];index=0;qIndex=0;score=0;hide('unitIntro');hide('resultPanel');show('cardPanel');drawCard()}
function drawCard(){const c=queue[index];$('cardCount').textContent=`${index+1} / ${queue.length}`;$('word').textContent=c.word;$('example').textContent=c.example;$('meaning').textContent=c.es;$('translation').textContent=c.translation;$('audioStatus').textContent='';hide('answer');show('reveal')}
function cardNext(known){save(queue[index],known);index++;if(index<queue.length)drawCard();else{hide('cardPanel');show('quizPanel');drawQuiz()}}
function drawQuiz(){const c=queue[qIndex];$('quizCount').textContent=`${qIndex+1} / ${queue.length}`;$('quizPrompt').textContent=c.prompt;$('feedback').textContent='';$('feedback').className='feedback';hide('next');$('choices').replaceChildren();const choices=[...c.choices],shift=qIndex%choices.length;choices.push(...choices.splice(0,shift));for(const choice of choices){const b=document.createElement('button');b.type='button';b.className='option';b.textContent=choice.label;b.addEventListener('click',()=>answer(c,choice,b));$('choices').append(b)}}
function answer(c,choice,btn){if(!$('next').classList.contains('hidden'))return;const ok=choice.correct;if(ok)score++;else save(c,false);for(const b of $('choices').children){b.disabled=true;if(b.textContent===c.word)b.classList.add('correct')}if(!ok)btn.classList.add('wrong');$('feedback').textContent=ok?'Correcto.':`La respuesta es “${c.word}”. ${c.es}.`;$('feedback').classList.add(ok?'ok':'no');show('next');$('next').textContent=qIndex===queue.length-1?'Ver resultado →':'Siguiente →'}
function finish(){hide('quizPanel');show('resultPanel');$('score').textContent=`${score} de ${queue.length} respuestas correctas.`;const due=dueCards().length;$('due').textContent=due?`Tienes ${due} palabra${due===1?'':'s'} para repasar. Las que falles vuelven antes.`:'Las palabras que te hayan costado volverán antes. Puedes regresar mañana.';$('reviewDue').classList.toggle('hidden',due===0)}
function listen(){if(!('speechSynthesis' in window)){$('audioStatus').textContent='Este navegador no tiene voz. Puedes seguir sin audio.';return}const voices=speechSynthesis.getVoices();voice=voices.find(v=>v.lang.toLowerCase()==='en-gb')||voices.find(v=>v.lang.toLowerCase().startsWith('en-'))||null;const u=new SpeechSynthesisUtterance(queue[index].word);u.lang='en-GB';if(voice)u.voice=voice;u.rate=.85;u.onerror=()=>{$('audioStatus').textContent='No se ha podido reproducir el audio en este dispositivo.'};speechSynthesis.cancel();speechSynthesis.speak(u);$('audioStatus').textContent='Pronunciación con la voz del dispositivo.'}
async function init(){try{for(const level of ['B2','C1']){const r=await fetch(`unit-${level.toLowerCase()}.json`);if(!r.ok)throw Error('data');units[level]=await r.json();if(units[level].cards.length!==6)throw Error('data')}}catch{$('unitIntro').innerHTML='<h2>No se puede cargar la unidad ahora.</h2><p>Prueba a actualizar la página.</p>';return}document.querySelectorAll('.level').forEach(b=>b.addEventListener('click',()=>chooseLevel(b.dataset.level)));$('start').addEventListener('click',()=>{const due=dueCards();start(due.length?due:units[level].cards)});$('reveal').addEventListener('click',()=>{hide('reveal');show('answer')});$('hard').addEventListener('click',()=>cardNext(false));$('easy').addEventListener('click',()=>cardNext(true));$('listen').addEventListener('click',listen);$('next').addEventListener('click',()=>{qIndex++;if(qIndex<queue.length)drawQuiz();else finish()});$('reviewDue').addEventListener('click',()=>start(dueCards()));$('restart').addEventListener('click',()=>start(units[level].cards));overview()}
init();
