'use strict';
const $=id=>document.getElementById(id),DAY=86400000,KEY='scalego:vocab:v1';
let units={},topics={},level='A1',topicId=null,queue=[],index=0,qIndex=0,score=0,voice=null,studyMode=true;
const LEVELS=['A1','A2','B1','B2','C1','C2'];
const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today=()=>localDate(new Date());
const read=()=>{try{let d=JSON.parse(localStorage.getItem(KEY)||'{}');return d&&typeof d==='object'?d:{}}catch{return {}}};
const write=data=>{try{localStorage.setItem(KEY,JSON.stringify(data))}catch{}};
const show=id=>$(id).classList.remove('hidden'),hide=id=>$(id).classList.add('hidden');
const cardKey=c=>c._level+':'+c.id;
function chosenTopic(){return topics[level].find(t=>t.id===topicId)||topics[level][0]}
function topicCards(){const ids=new Set(chosenTopic().cards);return units[level].cards.filter(c=>ids.has(c.id))}
function dueCards(){const data=read();return topicCards().filter(c=>data[cardKey(c)]?.due && data[cardKey(c)].due<=today())}
function renderTopics(){const holder=$('topics');holder.replaceChildren();for(const t of topics[level]){const b=document.createElement('button');b.type='button';b.className='topic';b.textContent=t.title+' · '+t.cards.length;b.setAttribute('aria-pressed',String(t.id===topicId));b.addEventListener('click',()=>{topicId=t.id;overview()});holder.append(b)}}
function overview(){const t=chosenTopic(),due=dueCards().length;renderTopics();$('unitTag').textContent='TEMA · '+level;$('unitTitle').textContent=t.title;$('levelStatus').textContent=level+' · '+topics[level].length+' temas · '+units[level].cards.length+' palabras';$('unitDescription').textContent=`${t.cards.length} palabras. Primero tarjetas, después ${t.cards.length} preguntas. Elige otro tema para cambiar.`;$('reviewStatus').textContent=due?`${due} palabra${due===1?'':'s'} pendiente${due===1?'':'s'} hoy. Empezarás por ellas.`:'No tienes repasos pendientes hoy. Puedes practicar este tema.';document.querySelectorAll('.level').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.level===level)));$('restart').textContent='Estudiar este tema otra vez';show('unitIntro');['cardPanel','quizPanel','resultPanel'].forEach(hide)}
function chooseLevel(v){level=v;topicId=topics[v][0].id;overview()}
function save(c,known){const data=read(),id=cardKey(c),old=data[id]||{step:0};let step=known?Math.min((Number.isInteger(old.step)?old.step:0)+1,4):0;const days=[1,3,7,14,30];const when=new Date();when.setDate(when.getDate()+days[step]);data[id]={step,due:localDate(when)};write(data)}
function start(cards,study=true){queue=[...cards];index=0;qIndex=0;score=0;studyMode=study;hide('unitIntro');hide('resultPanel');if(study){show('cardPanel');hide('quizPanel');drawCard()}else{hide('cardPanel');show('quizPanel');drawQuiz()}}
function drawCard(){const c=queue[index];$('cardCount').textContent=`${c._level} · ${index+1} / ${queue.length}`;$('word').textContent=c.word;$('example').textContent=c.example;$('meaning').textContent=c.es;$('translation').textContent=c.translation;$('audioStatus').textContent='';hide('answer');show('reveal')}
function cardNext(known){save(queue[index],known);index++;if(index<queue.length)drawCard();else{hide('cardPanel');show('unitIntro');$('unitTitle').textContent='Ya has visto este tema';$('unitDescription').textContent='Ahora puedes comprobar lo aprendido. También puedes volver a mirar las tarjetas.';$('reviewStatus').textContent='';$('practice').focus()}}
function drawQuiz(){const c=queue[qIndex];$('quizCount').textContent=`${c._level} · ${qIndex+1} / ${queue.length}`;$('quizPrompt').textContent=c.prompt;$('feedback').textContent='';$('feedback').className='feedback';hide('next');$('choices').replaceChildren();const choices=[...c.choices],shift=qIndex%choices.length;choices.push(...choices.splice(0,shift));for(const choice of choices){const b=document.createElement('button');b.type='button';b.className='option';b.textContent=choice.label;b.addEventListener('click',()=>answer(c,choice,b));$('choices').append(b)}}
function answer(c,choice,btn){if(!$('next').classList.contains('hidden'))return;const ok=choice.correct;if(ok)score++;else save(c,false);for(const b of $('choices').children){b.disabled=true;if(b.textContent===c.word)b.classList.add('correct')}if(!ok)btn.classList.add('wrong');$('feedback').textContent=ok?'Correcto.':`La respuesta es “${c.word}”. ${c.es}.`;$('feedback').classList.add(ok?'ok':'no');show('next');$('next').textContent=qIndex===queue.length-1?'Ver resultado →':'Siguiente →'}
function finish(){hide('quizPanel');show('resultPanel');$('score').textContent=`${score} de ${queue.length} respuestas correctas.`;const due=dueCards().length;$('due').textContent=due?`Tienes ${due} palabra${due===1?'':'s'} para repasar. Las que falles vuelven antes.`:'Las palabras que te hayan costado volverán antes. Puedes regresar mañana.';$('reviewDue').classList.toggle('hidden',due===0)}
function listen(){if(!('speechSynthesis' in window)){$('audioStatus').textContent='Este navegador no tiene voz. Puedes seguir sin audio.';return}const voices=speechSynthesis.getVoices();voice=voices.find(v=>v.lang.toLowerCase()==='en-gb')||voices.find(v=>v.lang.toLowerCase().startsWith('en-'))||null;const u=new SpeechSynthesisUtterance(queue[index].word);u.lang='en-GB';if(voice)u.voice=voice;u.rate=.85;u.onerror=()=>{$('audioStatus').textContent='No se ha podido reproducir el audio en este dispositivo.'};speechSynthesis.cancel();speechSynthesis.speak(u);$('audioStatus').textContent='Pronunciación con la voz del dispositivo.'}
async function init(){try{const manifest=await fetch('topics.json?v=2');if(!manifest.ok)throw Error('topics');topics=await manifest.json();for(const level of LEVELS){const r=await fetch(`unit-${level.toLowerCase()}.json`);if(!r.ok)throw Error('data');units[level]=await r.json();if(!units[level].cards.length||!topics[level]?.length)throw Error('data');const ids=new Set(units[level].cards.map(c=>c.id));const assigned=topics[level].flatMap(t=>t.cards);if(new Set(assigned).size!==ids.size||assigned.some(id=>!ids.has(id)))throw Error('topics');for(const c of units[level].cards)c._level=level}}catch{$('unitIntro').innerHTML='<h2>No se puede cargar la unidad ahora.</h2><p>Prueba a actualizar la página.</p>';return}document.querySelectorAll('.level').forEach(b=>b.addEventListener('click',()=>chooseLevel(b.dataset.level)));topicId=topics[level][0].id;$('start').addEventListener('click',()=>{const due=dueCards();start(due.length?due:topicCards(),true)});$('practice').addEventListener('click',()=>start(topicCards(),false));$('reveal').addEventListener('click',()=>{hide('reveal');show('answer')});$('hard').addEventListener('click',()=>cardNext(false));$('easy').addEventListener('click',()=>cardNext(true));$('listen').addEventListener('click',listen);$('next').addEventListener('click',()=>{qIndex++;if(qIndex<queue.length)drawQuiz();else finish()});$('reviewDue').addEventListener('click',()=>start(dueCards()));$('restart').addEventListener('click',()=>start(topicCards(),true));overview()}
init();
