'use strict';
const SECTION=document.body.dataset.section, TYPES=SECTION==='repaso'?['notacion','enteros','fracciones']:[SECTION];
const $=id=>document.getElementById(id),rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,pick=a=>a[rand(0,a.length-1)];
function gcd(a,b){while(b)[a,b]=[b,a%b];return Math.abs(a)}
function f(n,d=1){if(d<0)n=-n,d=-d;const g=gcd(Math.abs(n),d);return [n/g,d/g]}
function add(a,b){return f(a[0]*b[1]+b[0]*a[1],a[1]*b[1])}
function sub(a,b){return f(a[0]*b[1]-b[0]*a[1],a[1]*b[1])}
function mul(a,b){return f(a[0]*b[0],a[1]*b[1])}
function div(a,b){return f(a[0]*b[1],a[1]*b[0])}
const fmt=a=>a[1]===1?String(a[0]):`${a[0]}/${a[1]}`;
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=rand(0,i);[a[i],a[j]]=[a[j],a[i]]}return a}
function exercise(type,i){if(type==='fracciones-sumas-restas')return fractionAddSub(i);if(type==='notacion')return science();if(type==='enteros')return integers();return fractions()}
function decimal(s,e){let [whole,frac='']=s.split('.'),digits=whole+frac,point=whole.length+e;if(point<=0)return '0,'+'0'.repeat(-point)+digits.replace(/^0+(?=\d)/,'');if(point>=digits.length)return digits+'0'.repeat(point-digits.length);return digits.slice(0,point)+','+digits.slice(point)}
function sci(m,e){return `${m.replace('.',',')} × 10^${e}`}
function science(){const kind=rand(0,2),n=rand(11,99),m=(n/10).toFixed(1),exp=pick([-6,-5,-4,-3,-2,2,3,4,5,6]);if(kind===0){const value=decimal(m,exp);return {type:'NOTACIÓN CIENTÍFICA',prompt:`Escribe ${value} en notación científica.`,correct:sci(m,exp),wrong:[sci(m,exp+1),sci(m,exp-1),sci((n/100).toFixed(2),exp)],explain:`La coma se desplaza ${Math.abs(exp)} lugares. El coeficiente debe quedar entre 1 y 10; el exponente es ${exp}.`}}
if(kind===1){return {type:'FORMA DECIMAL',prompt:`Pasa ${sci(m,exp)} a forma decimal.`,correct:decimal(m,exp),wrong:[decimal(m,exp+1),decimal(m,exp-1),decimal(m,-exp)],explain:`Mueve la coma ${Math.abs(exp)} lugares hacia ${exp>0?'la derecha':'la izquierda'}.`}}
const shift=pick([-2,-1,1,2]),badM=decimal(m,shift).replace(',','.'),badE=exp-shift;return {type:'CORRIGE LA NOTACIÓN',prompt:`Normaliza ${sci(badM,badE)}.`,correct:sci(m,exp),wrong:[sci(m,badE),sci(m,exp+shift),sci((n/100).toFixed(2),exp+1)],explain:`${badM.replace('.',',')} × 10^${badE} representa el mismo número que ${sci(m,exp)}; el coeficiente normalizado está entre 1 y 10.`}}
function integers(){const kind=rand(0,2),a=rand(4,18),b=rand(2,9),c=rand(2,8),d=rand(2,7);if(kind===0){const v=a-b*(c-d),flat=a-b*c-d;return {type:'ENTEROS Y PARÉNTESIS',prompt:`${a} − ${b} × (${c} − ${d}) = ?`,correct:String(v),wrong:[String(flat),String(a-b*(c+d)),String(a-b-c+d)],explain:`Primero (${c} − ${d}) = ${c-d}; luego ${b} × ${c-d} = ${b*(c-d)}; al final ${a} − ${b*(c-d)} = ${v}.`}}
if(kind===1){const v=-a+b*(c+d),flat=(-a+b)*c+d;return {type:'JERARQUÍA DE OPERACIONES',prompt:`−${a} + ${b} × (${c} + ${d}) = ?`,correct:String(v),wrong:[String(flat),String(-a+b*c+d),String(a+b*(c+d))],explain:`Primero el paréntesis (${c} + ${d}) = ${c+d}, después la multiplicación y al final la suma: ${v}.`}}
const q=rand(2,7),x=q*rand(3,8),v=x/q-c*(d-b);return {type:'DIVISIÓN Y SIGNOS',prompt:`${x} : ${q} − ${c} × (${d} − ${b}) = ?`,correct:String(v),wrong:[String((x/q-c)*(d-b)),String(x/q-c*d-b),String(x/q+c*(d-b))],explain:`${x} : ${q} = ${x/q} y (${d} − ${b}) = ${d-b}. Después, ${x/q} − ${c*(d-b)} = ${v}.`}}
function fractionAddSub(i){const a=f(rand(1,7),rand(2,9)),b=f(rand(1,7),rand(2,9)),sum=i%2===0,correct=sum?add(a,b):sub(a,b),prompt=`${fmt(a)} ${sum?'+':'−'} ${fmt(b)} = ?`,wrong=[sum?sub(a,b):add(a,b),f(a[0]+(sum?b[0]:-b[0]),a[1]+b[1]),mul(a,b)].map(fmt);return {type:'FRACCIONES',prompt,correct:fmt(correct),wrong,explain:`Busca un denominador común, ${sum?'suma':'resta'} los numeradores y simplifica. El resultado es ${fmt(correct)}.`}}
function fractions(){const kind=rand(0,3),a=f(rand(1,7),rand(2,9)),b=f(rand(1,7),rand(2,9)),c=f(rand(1,5),rand(2,9));let prompt,correct,wrong,explain;if(kind===0){correct=add(a,b);prompt=`${fmt(a)} + ${fmt(b)} = ?`;wrong=[f(a[0]+b[0],a[1]+b[1]),sub(a,b),mul(a,b)];explain=`Busca un denominador común, suma los numeradores y simplifica: ${fmt(correct)}.`}else if(kind===1){correct=sub(a,b);prompt=`${fmt(a)} − ${fmt(b)} = ?`;wrong=[f(a[0]-b[0],a[1]+b[1]),add(a,b),mul(a,b)];explain=`Usa un denominador común, resta los numeradores y simplifica: ${fmt(correct)}.`}else if(kind===2){correct=div(a,b);prompt=`${fmt(a)} : ${fmt(b)} = ?`;wrong=[mul(a,b),f(a[0]*b[0],a[1]+b[1]),div(b,a)];explain=`Dividir entre ${fmt(b)} equivale a multiplicar por su inversa. Resultado simplificado: ${fmt(correct)}.`}else{correct=sub(a,mul(b,c));prompt=`${fmt(a)} − (${fmt(b)} × ${fmt(c)}) = ?`;wrong=[mul(sub(a,b),c),add(a,mul(b,c)),mul(a,sub(b,c))];explain=`Primero multiplica dentro del paréntesis: ${fmt(b)} × ${fmt(c)} = ${fmt(mul(b,c))}. Después resta y simplifica: ${fmt(correct)}.`}return {type:'FRACCIONES',prompt,correct:fmt(correct),wrong:wrong.map(fmt),explain}}
let questions=[],index=0,score=0,answered=false;
function build(){questions=[];for(let i=0;i<12;i++)questions.push(exercise(TYPES[i%TYPES.length],i));index=0;score=0;draw()}
function draw(){const q=questions[index];answered=false;$('counter').textContent=`Ejercicio ${index+1} de ${questions.length} · ${score} aciertos`;$('type').textContent=q.type;$('problem').textContent=q.prompt;$('choices').replaceChildren();$('feedback').className='feedback hidden';$('next').classList.add('hidden');let options=[q.correct,...q.wrong.filter(x=>x!==q.correct)].filter((x,i,a)=>a.indexOf(x)===i);let delta=1;while(options.length<4){const candidate=q.type==='FRACCIONES'?fmt(add(f(...q.correct.split('/').map(Number)),f(delta++,12))):q.type==='FORMA DECIMAL'?decimal((Number(q.correct.replace(',','.'))+delta++).toFixed(1),0):q.type.includes('NOTACIÓN')?q.correct.replace(/\^(-?\d+)/,(_,n)=>'^'+(Number(n)+delta++)):String(Number(q.correct)+delta++);if(!options.includes(candidate))options.push(candidate)}shuffle(options).forEach(label=>{const b=document.createElement('button');b.className='option';b.type='button';b.textContent=label;b.addEventListener('click',()=>answer(label,b));$('choices').appendChild(b)})}
function answer(value,button){if(answered)return;answered=true;const q=questions[index],right=value===q.correct;if(right)score++;for(const b of $('choices').children){b.disabled=true;if(b.textContent===q.correct)b.classList.add('right')}if(!right)button.classList.add('wrong');$('counter').textContent=`Ejercicio ${index+1} de ${questions.length} · ${score} aciertos`;$('feedback').textContent=`${right?'Bien.':'La respuesta correcta es '+q.correct+'.'} ${q.explain}`;$('feedback').className='feedback'+(right?'':' bad');$('next').textContent=index===questions.length-1?'Ver resultado':'Siguiente ejercicio';$('next').classList.remove('hidden')}
$('next').addEventListener('click',()=>{index++;if(index<questions.length)draw();else{$('practice').classList.add('hidden');$('result').classList.remove('hidden');$('resultText').textContent=`${score} aciertos de ${questions.length}. Puedes empezar otra tanda con ejercicios nuevos.`}});
$('restart').addEventListener('click',()=>{$('result').classList.add('hidden');$('practice').classList.remove('hidden');build()});$('beginPractice').addEventListener('click',()=>{$('study').classList.add('hidden');$('practice').classList.remove('hidden');$('problem').focus()});$('backStudy').addEventListener('click',()=>{$('practice').classList.add('hidden');$('result').classList.add('hidden');$('study').classList.remove('hidden')});build();
